version: 1.0.{build}
shallow_clone: true
os: Visual Studio 2015
deploy: off

install:
  - echo Install!
  - mkdir c:\temp
  - cd c:\temp
  - ps: Start-FileDownload 'https://s3.amazonaws.com/pelican-public/3rdParty.zip'
  - 7z e 3rdParty.zip
  - dir

build_script:
  - echo Building osgEarth using appveyor

