version: 1.0.{build}
shallow_clone: true
os: Visual Studio 2015

install:
  - echo Install
  - mkdir c:\temp
  - cd c:\temp
  - ps: Start-FileDownload 'https://s3.amazonaws.com/pelican-public/3rdParty.zip'
  - ps: Start-FileDownload 'https://s3.amazonaws.com/pelican-public/OpenSceneGraph-dev.zip'  
  - ps: Start-FileDownload 'http://download.gisinternals.com/sdk/downloads/release-1900-x64-gdal-2-2-3-mapserver-7-0-7-libs.zip'    
  - 7z x 3rdParty.zip
  - 7z x OpenSceneGraph-dev.zip
  - 7z x release-1900-x64-gdal-2-2-3-mapserver-7-0-7-libs.zip -ogdal
  - cd C:\projects\osgearth

build_script:
  - set PATH=%PATH%;c:\temp\3rdParty;c:\temp\OpenSceneGraph-dev;c:\temp\gdal
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 14 2015 Win64" -DWIN32_USE_MP=ON -DCMAKE_INSTALL_PREFIX=c:\projects\osgearth\install
  - cmake --build . --target INSTALL --config Release
  - cd ..\install
  - 7z a osgearth.zip *

artifacts:
  - path: install\osgearth.zip
    name: osgearth

notifications:
  - provider: Slack
    incoming_webhook:
      secure: zkwiuuSbzeT16LPK7+7P6p87LHoC89MVonn7RXtmp0r3Zt1kcnb69NgZI/NmAyvhZh+4fZWWj+zfiv6bzIw1Hm/W8b8wEie81Ih4aLUqBZA=

